---
title: "Diagnóstico de modelos mistos"
subtitle: "MAE5896 - Modelos Mistos e suas Aplicações - 2023"
format: 
  revealjs:
    theme: solarized
---

## Introdução

### Artigo

Isabel Molina, Ayoub Saei, M. José Lombardía, Small Area Estimates of Labour Force Participation Under a Multinomial Logit Mixed Model. [https://doi.org/10.1111/j.1467-985X.2007.00493.x](https://doi.org/10.1111/j.1467-985X.2007.00493.x)

### Objetivo

Desenvolver uma nova metodologia para estimar características de desemprego ou emprego em áreas pequenas.

## Motivação

- O Eurostat exige dos países-membros informações estatísticas cada vez mais detalhadas sobre regiões geográficas menores;
- Por uma questão de custo, os estudos nacionais não são planejados para oferecer estimativas diretas precisas nesses pequenos domínios.

## Motivação

- Segundo o Serviço de Estatísticas Nacionais do Reino Unido, estimativas só são publicadas se tiverem um coeficiente de variação de até 20%;
- Para o ano de 2000, somente 75 das 406 estimativas diretas poderiam ser publicadas!

## Motivação

- Nesse artigo, os autores estudam métodos para obter estimativas mais precisas para os índices de desemprego, emprego e inatividade no Reino Unido;
- Intuitivamente, a ideia é aproximar as estimativas de distritos que sejam parecidos por meio de um modelo de regressão;
- As estimativas serão viesadas, porém suas variâncias pode ser substancialmente menor;

## Variáveis 

::: {style="font-size: 60%;"}
| Variável            | Descrição                                                                                 |
|---------------------|---------------------------------------------------------------------------------------------|
| AREA                | Autoridade unitária ou distrito de autoridade local: 1–406                                 |
| SEXAGE              | Categorias de sexo e idade: 1–6 (idade, [16,25], (25,40] e >40 anos; homens, 1, 2, 3; mulheres, 4, 5, 6) |
| GOR                 | Região do escritório governamental: 1–12                                                     |
| CLUSTER             | Classificação socioeconômica: 1–7 (1, áreas rurais; 2, periferia urbana; 3, costa e serviços; 4, Inglaterra próspera; 5, mineração, manufatura e indústria; 6, centros educacionais e exterior de Londres; 7, interior de Londres) |
| SAMP.UNEMPLOYED    | Total de indivíduos desempregados na amostra no grupo AREA–SEXAGE                            |
| SAMP.EMPLOYED      | Total de indivíduos empregados na amostra no grupo AREA–SEXAGE                              |
| SAMP.INACTIVE      | Total de indivíduos inativos na amostra no grupo AREA–SEXAGE                               |
| REG.UNEMPLOYED     | Total de indivíduos registrados em um escritório de desemprego no grupo AREA–SEXAGE         |
| TOTAL              | Número total de indivíduos no grupo AREA–SEXAGE                                            |
:::

## Modelo

Modelo logit multinomial com efeitos aleatórios de _área_.

$$
f(y_{di1}, y_{di2} \mid u_d) = \frac{m_{di}!}{y_{di1}! \cdot y_{di2}! \cdot y_{di3}!} \cdot p_{di1}^{y_{di1}} \cdot p_{di2}^{y_{di2}} \cdot p_{di3}^{y_{di3}}
$$
$$
\log{(p_{dij}/p_{di3})} = x_{di}\beta_j + u_d, \qquad j=1,2 \qquad i = 1,\dots ,6 \qquad d = 1,\dots,406
$$
$$
u_d \stackrel{iid}{\sim} N(0,\varphi)
$$

::: {style="font-size: 60%;"}

- $y_{di1}$, $y_{di2}$ e $y_{di3}$ denotam o número de desempregados, empregados e inativos amostrados, respectivamente.
- $m_{di} = y_{di1} + y_{di2} + y_{di3}$ representa o tamanho da amostra.
- $p_{di1}, p_{di2}, p_{di3}$ são as probabilidades respectivas de indivíduos desempregados, empregados e inativos. $\left(\sum_j p_{dij} = 1\right)$
- $x_{di}$ são as variáveis explicativas

:::

## Variáveis explicativas

- Log-proporção de REG.UNEMPLOYED.
- 22 indicadores (dummy) para categorias de GOR, CLUSTER e SEXAGE, com a última categoria de cada uma como referência base.
- Matriz de incidência construída ($X$):
  - Possui 24 colunas, incluindo um intercepto.
  - Indexada por $i = 1,…,6$ para a categoria SEXAGE e $d = 1,…,406$ para AREA.

- $u_d$ denota o efeito aleatório da área $d$.

## Diagnóstico de modelos mistos

## Análise de resíduos

## Desafios

## Conclusão


